"""add rider assignment fields

Revision ID: 6e07f6a120e7
Revises: eb3f94b5cb52
Create Date: 2026-06-05 15:38:30.285181

"""
from typing import Sequence, Union

from alembic import op  
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e07f6a120e7'
down_revision: Union[str, None] = 'eb3f94b5cb52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'orders',
        sa.Column('rider_id', sa.Integer(), nullable=True)
    )

    op.add_column(
        'orders',
        sa.Column(
            'assignment_status',
            sa.String(length=50),
            nullable=False,
            server_default='UNASSIGNED'
        )
    )

    op.alter_column(
        'orders',
        'assignment_status',
        server_default=None
    )

    op.create_foreign_key(
        'fk_orders_rider_id_riders_id',
        'orders',
        'riders',
        ['rider_id'],
        ['id']
    )

    op.create_index(
    'ix_orders_rider_id',
    'orders',
    ['rider_id']
)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_orders_rider_id_riders_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'assignment_status')
    op.drop_column('orders', 'rider_id')
    op.drop_index('ix_orders_rider_id', table_name='orders')
    # ### end Alembic commands ###
